import { useState } from 'react'
import { MOCK_ALERTS } from '../lib/mockData'

function generateMockReport(alert) {
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const timeStr = now.toLocaleTimeString('en-IN')

  return `CERT-In INCIDENT REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INCIDENT REPORT NO: CERT-IN/2026/${String(alert.id).padStart(4, '0')}/${Math.floor(Math.random()*9000)+1000}
DATE OF REPORT: ${dateStr}
TIME: ${timeStr} IST
REPORTED BY: AcademiaSentinel OSINT Platform (SIH 2026 PS 26202)
CLASSIFICATION: ${alert.severity} — ${alert.threat_type.replace(/_/g, ' ')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 1: INCIDENT OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Incident Title   : ${alert.title}
Affected Entity  : ${alert.institution_name} (${alert.institution_domain})
Threat Category  : ${alert.threat_type.replace(/_/g, ' ')}
Severity Level   : ${alert.severity}
Detection Source : ${alert.source}
Detected At      : ${new Date(alert.detected_at).toLocaleString('en-IN')}
Current Status   : ${alert.status}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 2: INCIDENT DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${alert.description}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 3: IMPACT ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Confidentiality Impact : ${alert.severity === 'CRITICAL' ? 'HIGH — Sensitive data may be publicly exposed' : alert.severity === 'HIGH' ? 'MEDIUM — Partial data exposure likely' : 'LOW — Limited exposure'}
Integrity Impact       : ${alert.threat_type === 'RANSOMWARE' ? 'CRITICAL — Data encryption reported' : alert.threat_type === 'FAKE_DOCUMENT' ? 'HIGH — Fraudulent documents in circulation' : 'MEDIUM — Data authenticity may be compromised'}
Availability Impact    : ${alert.threat_type === 'RANSOMWARE' ? 'HIGH — Systems inaccessible' : 'LOW — Systems operational'}
Compliance Concern     : ${alert.threat_type === 'DATA_BREACH' || alert.threat_type === 'CREDENTIAL_DUMP' ? 'PDPB 2023 notification may be required within 72 hours' : 'IT Act 2000 Section 66 applies'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 4: RECOMMENDED IMMEDIATE ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Notify the institution's IT security / CISO team immediately
2. ${alert.threat_type === 'CREDENTIAL_DUMP' ? 'Force password resets for all potentially affected accounts and enable MFA' : alert.threat_type === 'EXAM_LEAK' ? 'Alert examination authority and issue takedown notices to hosting platforms' : alert.threat_type === 'RANSOMWARE' ? 'Isolate affected systems, do NOT pay ransom, restore from clean backup' : 'Preserve digital evidence and document all findings for forensic analysis'}
3. File complaint with local Cyber Crime Cell under IT Act 2000
4. Submit threat indicators to CERT-In via https://www.cert-in.org.in
5. ${alert.threat_type === 'DATA_BREACH' || alert.threat_type === 'CREDENTIAL_DUMP' ? 'Notify affected individuals and issue public advisory per PDPB 2023' : 'Monitor for follow-up attacks on the same institution'}
6. Engage forensic investigation team to determine breach root cause
7. Update incident status in AcademiaSentinel dashboard when resolved

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 5: REGULATORY REFERENCES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

• IT Act 2000 — Section 66, 66C, 66D (as applicable)
• Personal Data Protection Bill 2023 — Breach notification requirements
• NCIIPC Guidelines for Critical Sector Protection
• UGC/AICTE Cyber Security Advisory for Higher Education Institutions
• CERT-In Directions 2022 — Mandatory incident reporting within 6 hours

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 6: POINT OF CONTACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Platform   : AcademiaSentinel — SIH 2026 PS 26202
Authority  : AICTE / Ministry of Education Cyber Cell
CERT-In    : https://www.cert-in.org.in | +91-1800-11-4949
Nodal CERT : education-cert@cert-in.org.in

Report generated by AcademiaSentinel AI · ${dateStr} ${timeStr}
This report is AI-assisted and should be reviewed by a qualified cybersecurity professional before submission.
`
}

export default function ReportGen() {
  const alerts = MOCK_ALERTS.filter(a => a.severity === 'CRITICAL' || a.severity === 'HIGH')
  const [selectedAlert, setSelectedAlert] = useState(null)
  const [report, setReport] = useState('')
  const [loading, setLoading] = useState(false)

  async function generateReport() {
    if (!selectedAlert) return
    setLoading(true); setReport('')
    await new Promise(r => setTimeout(r, 1500))
    setReport(generateMockReport(selectedAlert))
    setLoading(false)
  }

  function downloadReport() {
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url
    a.download = `cert-in-report-${selectedAlert?.institution_name?.replace(/\s+/g, '-')}-${Date.now()}.txt`
    a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 20, fontWeight: 800, color: '#fff', marginBottom: 4 }}>CERT-In Incident Report Generator</h1>
      <div style={{ color: 'var(--text2)', fontSize: 12, marginBottom: 20 }}>
        Auto-generate CERT-In compliant incident reports · IT Act 2000 · PDPB 2023
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: 20 }}>
        {/* Alert selector */}
        <div>
          <div style={{ fontWeight: 700, color: '#fff', marginBottom: 10, fontSize: 13 }}>Select Incident</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {alerts.map(a => (
              <div key={a.id} onClick={() => { setSelectedAlert(a); setReport('') }} style={{
                background: selectedAlert?.id === a.id ? '#3b82f615' : 'var(--surface)',
                border: `1px solid ${selectedAlert?.id === a.id ? '#3b82f6' : 'var(--border)'}`,
                borderRadius: 8, padding: '10px 12px', cursor: 'pointer'
              }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: '#fff', marginBottom: 4 }}>
                  {a.title?.slice(0, 52)}{a.title?.length > 52 ? '...' : ''}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <span className={`badge badge-${a.severity}`}>{a.severity}</span>
                  <span style={{ fontSize: 10, color: 'var(--text2)' }}>{a.institution_name}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Report area */}
        <div>
          <div style={{ display: 'flex', gap: 10, marginBottom: 12 }}>
            <button onClick={generateReport} disabled={!selectedAlert || loading} style={{
              background: !selectedAlert || loading ? '#1e2d45' : '#3b82f6',
              color: '#fff', border: 'none', borderRadius: 8, padding: '8px 16px',
              cursor: !selectedAlert || loading ? 'not-allowed' : 'pointer',
              fontWeight: 700, fontSize: 13
            }}>
              {loading ? '⏳ Generating...' : '📋 Generate CERT-In Report'}
            </button>
            {report && (
              <button onClick={downloadReport} style={{
                background: '#22c55e20', color: '#22c55e', border: '1px solid #22c55e40',
                borderRadius: 8, padding: '8px 16px', cursor: 'pointer', fontWeight: 700, fontSize: 13
              }}>⬇️ Download .txt</button>
            )}
          </div>

          {!selectedAlert && !report && (
            <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: 40, textAlign: 'center', color: 'var(--text2)' }}>
              <div style={{ fontSize: 32, marginBottom: 12 }}>📋</div>
              <div>Select an incident from the left to generate a CERT-In report</div>
            </div>
          )}

          {report && (
            <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: 20 }}>
              <div style={{ fontWeight: 700, color: '#fff', marginBottom: 12, display: 'flex', justifyContent: 'space-between' }}>
                <span>Generated CERT-In Report</span>
                <span style={{ fontSize: 11, color: '#22c55e', fontWeight: 600 }}>✓ AI Generated · {new Date().toLocaleString('en-IN')}</span>
              </div>
              <pre style={{
                fontFamily: 'monospace', fontSize: 11, color: 'var(--text)', lineHeight: 1.7,
                whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxHeight: 520, overflow: 'auto'
              }}>{report}</pre>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
